- name: install openjdk and apache-tomcat
  hosts: all
  user: root

  tasks:

    - name: Install OpenJDK 8
      apt: name=openjdk-8-jre-headless

    - name: Download Tomcat
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
        dest: /

    - name: Extract archive
      unarchive:
        src: /apache-tomcat-8.5.78.tar.gz
        dest: /
        remote_src: yes