pipeline {
    agent any

    stages {
        stage ('Clone') {
            steps {
                git branch: 'master', url: "https://github.com/henrik-olvr/Calculator-Java.git"
            }
        }

        stage ('Test') {
            steps{
                sh './gradlew test'
            }
        }

        stage ('Build') {
            steps{
                sh './gradlew build'
            }
        }

        stage ('Artifactory Deploy') {
            steps {
                rtUpload (
                    serverId: "jfrog-artifactory-server",
                    spec: '''{
                        "files": [
                            {
                                "pattern": "build/libs/calculator-app.war",
                                "target": "art1-gradle-release-local"
                            }
                        ]
                    }'''
                )
            }
        }
    }
}